### ISSUE TITLE
Map Layers & Overlay Ideas

### ISSUE THREAD

**Issue by Darakah** [Darakah/obsidian-map#10]
Ignore Issue, used as Discussion / Idea tracking / Design of `Map layers & Overlay` handling.

**Comment by Darakah** [comment]
Getting Ideas from various sources:
- https://azgaar.github.io/Fantasy-Map-Generator/
- https://www.worldanvil.com/
- https://www.wonderdraft.net/


## Tile Layers:

1. Political Map
2. Cultural Map
3. Religious Map
4. Provinces Map
5. Biomass Map
6. Height Map
7. Base Landmass Map
8. City Design / Detail (deepest layer)

## Overlay Layers:

1. Emblems / Households 
2. Borders (Nation bold / Province thin)
3. Main Routes (Different colors to represent different categories i.e. Train, cement and so on + width / style)
4. Secondary Routes
5. Sea routes
6. Arial routes
7. Military (Camps / Castles / Troops and so on using different marker Icons)
8. Rivers (Use width / color to have different categories)

**Comment by Darakah** [comment]
Each of these should be time tagged to be able to filter and interactively display on map. 

Instead of saving tile images from `leaflet map paint` into plugin data, export same as with geoJson from `FreeDraw` and make the name of the file the combination of information `TimeStart_TimeEnd_Layer_Zoom_Lat_Long_Lat_Long.png` with the first 3 elements must be specified by the user, these are then placed in a tiles folder from which the plugin will automatically read the tiles and display them accordingly.

**Comment by derentis** [comment]
This plugin looks awesome.  How can I install it in Obsidian?  It doesn't show up on the list in the community plugin browser.

I started looking at WorldSpinner and while that was my absolute favorite ready-to-use world generator. I wanted to make sure that the world I was creating had believable geographic features.

I went down the rabbit hole and start watching a whole bunch of videos from:

- Artifexian https://www.youtube.com/watch?v=TQvwgPFSN-I&list=PLduA6tsl3gyjUh9mMXfevCsaDiFKg9I47&index=1

- Biblaridion https://www.youtube.com/watch?v=egzZv8tqT_k&list=PL6xPxnYMQpquNuaEffJzjGjMsr6VktCYl

Incredibly interesting videos and good food-for-thought for creating more believable fantasy worlds.

This led me to GPlates (https://www.gplates.org/).  Try using GPlates to create your base map then export as SVG to be used with this plugin - I reckon that'll be an awesome combo.

I'm a big fan of data portability - will the layer data be exportable?

**Comment by Darakah** [comment]
@derentis  Hello! 

- `will the layer data be exportable?`

Which layer data are you referring to? Everything that you can add to the map currently can be exported. These are in 3 main categories:
       * Leaflet Draw (draw tools on the top right) which will be exported as a geojson file (by pressing the download button in the buttom right)
       * Leaflet Free Draw (draw tools inside the Map Control Pane in the top right). This one also exports to a geojson file, its advantage over leaflet draw is that it is much easier to use as it will add the points to fit the shape that you draw instead of having to click them one point at a time.
       * Leaflet Paint which exports the focused map view as a png. This is the one I am currently using, as the exported png's name includes the information which lets it be displayed again on the map in that exact position as I explain above. This means that the png can be modified using any tool such as Wondercraft / Photoshop or whatever else. This allows me to define many layers such as: roads, rivers, geography, city map, political, religious, cultural and so on and so forth. The control layer to which the png is added is user specified (first argument of the png name) and can be linked to an obsidian note (specified by adding the path after the last coordinate parameter in the png name). 

- `Other data`?

Obsidian notes related to a location can be added as a marker automatically to the note by specifying an information block (check the v0.5.0 release notes in the README). These markers can be organized into new layers and the markers customized as desired.

- `Can svg be plotted?` 

yes, it can simply be added to the current version by reading tiles that have `svg` and `png` (instead of only png) with the same name format as the current tiles to know where to place it. 

- `Installation`?

I didn't place it on the community plugins as it is only for those that might be interested (which are few) and the `main.js` is kinda of big (~ 14 mb for v.0.5.0). 

You can install it by downloading the latest release `main.js`, `style.css` & `manifest.json` from https://github.com/Darakah/obsidian-map/releases/tag/0.5.0
Put all three files in a folder (call it something like obsidian-map ... the name doesn't matter though), then place this folder inside the plugins folder of your vault. After that, refresh the plugins tab and it should appear there to be activated. 

After this, if you already have your map tiles simply specify the folder / structure where they are located in the settings tab otherwise it will just be a grey empty map.
